device_name = "Usb KeyBoard Usb KeyBoard"

[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_LEFTCTRL"]
tap = ["KEY_ESC"]

[[remap]]
input = ["KEY_RIGHTALT"]
output = ["KEY_BACKSPACE"]
mode = "normal"


[[remap]]
input = ["KEY_LEFTALT", "KEY_K"]
output = ["KEY_UP"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_J"]
output = ["KEY_DOWN"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_H"]
output = ["KEY_LEFT"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_L"]
output = ["KEY_RIGHT"]


[[remap]]
input = ["KEY_LEFTALT", "KEY_F"]
output = ["KEY_MINUS"]


[[remap]]
input = ["KEY_LEFTALT", "KEY_LEFTBRACE"]
output = ["KEY_LEFTSHIFT", "KEY_9"]


[[remap]]
input = ["KEY_LEFTALT", "KEY_RIGHTBRACE"]
output = ["KEY_LEFTSHIFT", "KEY_0"]


# test modes
# [[remap]]
# input = ["KEY_B"]
# output = ["KEY_LEFTCTRL", "KEY_LEFT"]


# [[dual_role]]
# input = "KEY_RIGHTALT"
# hold = ["KEY_LEFTSHIFT"]
# tap = ["KEY_SPACE"]

# [[remap]]
# input = ["KEY_LEFTALT", "KEY_F8"]
# # When our `input` is matched, our list of `output` is prevented from
# # matching as the `input` of subsequent rules.
# output = ["KEY_F8"]
